language: c
script: bash -ex .travis-ci.sh
env:
  - OCAML_VERSION=4.02
  - OCAML_VERSION=4.02 DEPOPTS="lwt"
  - OCAML_VERSION=4.02 DEPOPTS="async"
  - OCAML_VERSION=4.01 DEPOPTS="async lwt"
  - OCAML_VERSION=4.01 DEPOPTS="camlp4"
