language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PACKAGE="cstruct"
  matrix:
    - OCAML_VERSION=4.02 REVDEPS=tls
    - OCAML_VERSION=4.02 DEPOPTS="lwt" REVDEPS="dns irmin"
    - OCAML_VERSION=4.02 DEPOPTS="async"
    - OCAML_VERSION=4.01 DEPOPTS="async lwt" REVDEPS=mirage
    - OCAML_VERSION=4.01 DEPOPTS="camlp4"
